/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastrarproduto;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author GR2
 */
public class FormProduto extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrarproduto
     */
    public FormProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupotipo = new javax.swing.ButtonGroup();
        grupovenda = new javax.swing.ButtonGroup();
        grupoestoque = new javax.swing.ButtonGroup();
        grupopromocao = new javax.swing.ButtonGroup();
        idprodutos = new javax.swing.JLabel();
        idProdutotxt = new javax.swing.JTextField();
        buscarprodutos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nomeProduto = new javax.swing.JTextPane();
        dadosprodutos = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        nomereduzido = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescricao = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtnomereduzido = new javax.swing.JTextPane();
        unidade = new javax.swing.JLabel();
        unidades = new javax.swing.JComboBox<>();
        apresentacao = new javax.swing.JLabel();
        comissao = new javax.swing.JLabel();
        codigodebarras = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtapresentacao = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtcomissao = new javax.swing.JTextPane();
        txtcodigodebarras = new javax.swing.JScrollPane();
        txtcodigo = new javax.swing.JTextPane();
        tipo = new javax.swing.JLabel();
        btproduto = new javax.swing.JRadioButton();
        btservico = new javax.swing.JRadioButton();
        vendadoproduto = new javax.swing.JLabel();
        btquantidade = new javax.swing.JRadioButton();
        btvalor = new javax.swing.JRadioButton();
        estoqueonline = new javax.swing.JLabel();
        btestoquesim = new javax.swing.JRadioButton();
        btestoquenao = new javax.swing.JRadioButton();
        convenio = new javax.swing.JLabel();
        cxdesconto = new javax.swing.JCheckBox();
        valoresdevarejo = new javax.swing.JLabel();
        valordecompra = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtvalordecompra = new javax.swing.JTextPane();
        custooperacional = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtcustooperacional = new javax.swing.JTextPane();
        margemdelucro = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtmargemdelucro = new javax.swing.JTextPane();
        valoravista = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtvaloravista = new javax.swing.JTextPane();
        desconto = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtdesconto = new javax.swing.JTextPane();
        posicaodeestoque = new javax.swing.JLabel();
        estoqueminimo = new javax.swing.JLabel();
        txtestoquemaximo = new javax.swing.JScrollPane();
        txtestoqueminimo = new javax.swing.JTextPane();
        estoquemaximo = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtaumentomaximo = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtultimoaumento = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        sair = new javax.swing.JButton();
        listar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        promocao = new javax.swing.JLabel();
        btpromocaonao = new javax.swing.JRadioButton();
        btpromocaosim = new javax.swing.JRadioButton();
        valordapromocao = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtvalordapromocao = new javax.swing.JTextPane();
        validadedapromocao = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtvalidadedapromocao = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idprodutos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        idprodutos.setForeground(new java.awt.Color(0, 0, 204));
        idprodutos.setText("Identificação do Produto");

        idProdutotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdutotxtActionPerformed(evt);
            }
        });

        buscarprodutos.setText("Buscar");
        buscarprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarprodutosActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(nomeProduto);

        dadosprodutos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        dadosprodutos.setForeground(new java.awt.Color(0, 0, 204));
        dadosprodutos.setText("Dados Básicos");

        descricao.setText("Descrição:");

        nomereduzido.setText("Nome Reduzido:");

        jScrollPane2.setViewportView(txtdescricao);

        jScrollPane3.setViewportView(txtnomereduzido);

        unidade.setText("Unidade:");

        unidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centímetro", "Metro", "Litro" }));
        unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadesActionPerformed(evt);
            }
        });

        apresentacao.setText("Apresentação:");

        comissao.setText("Comissão:");

        codigodebarras.setText("Código de Barras:");

        jScrollPane4.setViewportView(txtapresentacao);

        jScrollPane5.setViewportView(txtcomissao);

        txtcodigodebarras.setViewportView(txtcodigo);

        tipo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tipo.setForeground(new java.awt.Color(0, 0, 204));
        tipo.setText("Tipo");

        grupotipo.add(btproduto);
        btproduto.setSelected(true);
        btproduto.setText("Produto");
        btproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprodutoActionPerformed(evt);
            }
        });

        grupotipo.add(btservico);
        btservico.setText("Serviço");

        vendadoproduto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        vendadoproduto.setForeground(new java.awt.Color(0, 0, 204));
        vendadoproduto.setText("Venda do Produto");

        grupovenda.add(btquantidade);
        btquantidade.setSelected(true);
        btquantidade.setText("Quantidade");
        btquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquantidadeActionPerformed(evt);
            }
        });

        grupovenda.add(btvalor);
        btvalor.setText("Valor");

        estoqueonline.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        estoqueonline.setForeground(new java.awt.Color(0, 0, 204));
        estoqueonline.setText("Estoque On Line");

        grupoestoque.add(btestoquesim);
        btestoquesim.setText("Sim");

        grupoestoque.add(btestoquenao);
        btestoquenao.setSelected(true);
        btestoquenao.setText("Não");

        convenio.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        convenio.setForeground(new java.awt.Color(0, 0, 204));
        convenio.setText("Convênio");

        cxdesconto.setText("Desconto");
        cxdesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxdescontoActionPerformed(evt);
            }
        });

        valoresdevarejo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        valoresdevarejo.setForeground(new java.awt.Color(0, 0, 204));
        valoresdevarejo.setText("Valores de Varejo");

        valordecompra.setText("Valor de Compra:");

        jScrollPane6.setViewportView(txtvalordecompra);

        custooperacional.setText("Custo Operacional:");

        jScrollPane7.setViewportView(txtcustooperacional);

        margemdelucro.setText("Margem de Lucro:");

        jScrollPane8.setViewportView(txtmargemdelucro);

        valoravista.setText("Valor à Vista:");

        jScrollPane9.setViewportView(txtvaloravista);

        desconto.setText("Desconto:");

        jScrollPane10.setViewportView(txtdesconto);

        posicaodeestoque.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        posicaodeestoque.setForeground(new java.awt.Color(0, 0, 204));
        posicaodeestoque.setText("Posição de Estoque");

        estoqueminimo.setText("Estoque Mínimo:");

        txtestoquemaximo.setViewportView(txtestoqueminimo);

        estoquemaximo.setText("Estoque Máximo:");

        jScrollPane14.setViewportView(txtaumentomaximo);

        jLabel4.setText("Último Aumento:");

        jScrollPane15.setViewportView(txtultimoaumento);

        sair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sair.setText("SAIR");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        listar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listar.setText("LISTAR");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        alterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alterar.setText("ALTERAR");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        remover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        remover.setText("REMOVER");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        cadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(listar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        promocao.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        promocao.setForeground(new java.awt.Color(0, 0, 204));
        promocao.setText("Promoção:");

        grupopromocao.add(btpromocaonao);
        btpromocaonao.setSelected(true);
        btpromocaonao.setText("Não");
        btpromocaonao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpromocaonaoActionPerformed(evt);
            }
        });

        grupopromocao.add(btpromocaosim);
        btpromocaosim.setText("Sim");
        btpromocaosim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpromocaosimActionPerformed(evt);
            }
        });

        valordapromocao.setText("Valor da Promoção:");

        jScrollPane11.setViewportView(txtvalordapromocao);

        validadedapromocao.setText("Validade da Promoção:");

        jScrollPane12.setViewportView(txtvalidadedapromocao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validadedapromocao)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valordapromocao)
                    .addComponent(btpromocaosim)
                    .addComponent(btpromocaonao)
                    .addComponent(promocao))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(promocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btpromocaonao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btpromocaosim)
                .addGap(18, 18, 18)
                .addComponent(valordapromocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(validadedapromocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(unidades, 0, 241, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(apresentacao)
                                                .addGap(130, 130, 130)
                                                .addComponent(comissao))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(unidade)
                                        .addGap(590, 590, 590)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigodebarras)
                                    .addComponent(txtcodigodebarras, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estoqueminimo)
                                    .addComponent(txtestoquemaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estoquemaximo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane15)
                                        .addGap(274, 274, 274))
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descricao)
                                .addGap(302, 302, 302)
                                .addComponent(nomereduzido)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btproduto)
                                            .addComponent(btservico))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(convenio)
                                            .addComponent(cxdesconto))
                                        .addGap(92, 92, 92))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(posicaodeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(valordecompra)
                                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(custooperacional))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(margemdelucro))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(valoravista)
                                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(desconto)
                                                    .addComponent(jScrollPane10)))
                                            .addComponent(valoresdevarejo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(127, 127, 127)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addComponent(vendadoproduto))
                                                    .addComponent(btquantidade)
                                                    .addComponent(btvalor))
                                                .addGap(75, 75, 75)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btestoquesim)
                                                    .addComponent(btestoquenao)
                                                    .addComponent(estoqueonline))))
                                        .addGap(57, 57, 57)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dadosprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idprodutos))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idProdutotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarprodutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idprodutos)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idProdutotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buscarprodutos))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(dadosprodutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descricao)
                            .addComponent(nomereduzido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unidade)
                            .addComponent(apresentacao)
                            .addComponent(comissao)
                            .addComponent(codigodebarras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcodigodebarras, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(unidades))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(vendadoproduto)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btquantidade)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btvalor))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tipo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btproduto)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btservico)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(convenio)
                                        .addGap(3, 3, 3)
                                        .addComponent(cxdesconto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(estoqueonline)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btestoquenao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btestoquesim)))
                                .addGap(35, 35, 35)
                                .addComponent(valoresdevarejo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valordecompra)
                                    .addComponent(custooperacional)
                                    .addComponent(margemdelucro)
                                    .addComponent(valoravista)
                                    .addComponent(desconto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(posicaodeestoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(estoqueminimo)
                                    .addComponent(estoquemaximo)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtestoquemaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadesActionPerformed

    private void btpromocaonaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpromocaonaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btpromocaonaoActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed

        Produto produto = new Produto();

        produto.setId(listaDeProdutos.size() == 0 ? 1 : listaDeProdutos.size() + 1);
        produto.setIsConvenio(cxdesconto.isSelected());
        produto.setDescricao(txtdescricao.getText());
        produto.setNome(txtnomereduzido.getText());
        produto.setUnidade((String) unidades.getSelectedItem());
        produto.setApresentacao(txtapresentacao.getText());
        produto.setComissao(Double.parseDouble(txtcomissao.getText()));
        produto.setCodigoBarras(txtcodigo.getText());
        produto.setTipoProduto(btproduto.isSelected() ? 0 : 1);
        produto.setVendaDoProduto(btquantidade.isSelected() ? 0 : 1);
        produto.setIsEstoqueOnline(btestoquesim.isSelected());
        produto.setIsPromocao(btpromocaosim.isSelected());
        produto.setValorDeCompra(Double.parseDouble(txtvalordecompra.getText()));
        produto.setCustoOperacional(Double.parseDouble(txtcustooperacional.getText()));
        produto.setMargemDeLucro(Double.parseDouble(txtmargemdelucro.getText()));
        produto.setValorVista(Double.parseDouble(txtvaloravista.getText()));
        produto.setDesconto(Double.parseDouble(txtdesconto.getText()));
        produto.setValorPromocao(Double.parseDouble(txtvalordapromocao.getText()));
        produto.setEstoqueMin(Integer.parseInt(txtestoqueminimo.getText()));
        produto.setEstoqueMax(Integer.parseInt(txtaumentomaximo.getText()));
        produto.setUltimoAumento(txtultimoaumento.getText());
        produto.setValidadePromocao(txtvalidadedapromocao.getText());

        listaDeProdutos.add(produto);
        limparCampos();

    }//GEN-LAST:event_cadastrarActionPerformed

    public void limparCampos() {

        txtdescricao.setText("");
        cxdesconto.setSelected(false);
        txtnomereduzido.setText("");
        unidades.setSelectedItem((Object) "Centímetro");
        txtapresentacao.setText("");
        txtcomissao.setText("");
        txtcodigo.setText("");
        btproduto.setSelected(true);
        btservico.setSelected(false);
        btquantidade.setSelected(true);
        btvalor.setSelected(false);
        btestoquesim.setSelected(false);
        btestoquenao.setSelected(true);
        btpromocaosim.setSelected(false);
        btpromocaonao.setSelected(true);
        txtvalordecompra.setText("");
        txtcustooperacional.setText("");
        txtmargemdelucro.setText("");
        txtvaloravista.setText("");
        txtdesconto.setText("");
        txtvalordapromocao.setText("");
        txtestoqueminimo.setText("");
        txtaumentomaximo.setText("");
        txtultimoaumento.setText("");
        txtvalidadedapromocao.setText("");

    }

    private void cxdescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxdescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxdescontoActionPerformed

    private void btprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btprodutoActionPerformed

    private void btquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btquantidadeActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed

        String listagem = "Itens Listados: " + "\n" + "\n";

        for (Produto produto : listaDeProdutos) {
            listagem += produto.getId() + "." + " Nome: " + produto.getNome() + "\n"
                    + "Descrição: " + produto.getDescricao() + "\n" + "\n";
        }

        System.out.println(listagem);
        JOptionPane.showMessageDialog(null, listagem);

    }//GEN-LAST:event_listarActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        
        int idProdutoInformado = idProdutotxt.getText().matches("^[0-9]*$") ? Integer.parseInt(idProdutotxt.getText()) : 0;
        listaDeProdutos.removeIf(x -> x.getId() == idProdutoInformado);
        limparCampos();
        
    }//GEN-LAST:event_removerActionPerformed

    private void btpromocaosimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpromocaosimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btpromocaosimActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed

        int idProdutoInformado = idProdutotxt.getText().matches("^[0-9]*$") ? Integer.parseInt(idProdutotxt.getText()) : 0;

        for (Produto produto : listaDeProdutos) {

            if (produto.getId() == idProdutoInformado) {

                produto.setIsConvenio(cxdesconto.isSelected());
                produto.setDescricao(txtdescricao.getText());
                produto.setNome(txtnomereduzido.getText());
                produto.setUnidade((String) unidades.getSelectedItem());
                produto.setApresentacao(txtapresentacao.getText());
                produto.setComissao(Double.parseDouble(txtcomissao.getText()));
                produto.setCodigoBarras(txtcodigo.getText());
                produto.setTipoProduto(btproduto.isSelected() ? 0 : 1);
                produto.setVendaDoProduto(btquantidade.isSelected() ? 0 : 1);
                produto.setIsEstoqueOnline(btestoquesim.isSelected());
                produto.setIsPromocao(btpromocaosim.isSelected());
                produto.setValorDeCompra(Double.parseDouble(txtvalordecompra.getText()));
                produto.setCustoOperacional(Double.parseDouble(txtcustooperacional.getText()));
                produto.setMargemDeLucro(Double.parseDouble(txtmargemdelucro.getText()));
                produto.setValorVista(Double.parseDouble(txtvaloravista.getText()));
                produto.setDesconto(Double.parseDouble(txtdesconto.getText()));
                produto.setValorPromocao(Double.parseDouble(txtvalordapromocao.getText()));
                produto.setEstoqueMin(Integer.parseInt(txtestoqueminimo.getText()));
                produto.setEstoqueMax(Integer.parseInt(txtaumentomaximo.getText()));
                produto.setUltimoAumento(txtultimoaumento.getText());
                produto.setValidadePromocao(txtvalidadedapromocao.getText());

            }
        }

        limparCampos();
        
    }//GEN-LAST:event_alterarActionPerformed

    private void idProdutotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProdutotxtActionPerformed
    }//GEN-LAST:event_idProdutotxtActionPerformed

    private void buscarprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarprodutosActionPerformed

        Produto produto = null;
        int idProdutoInformado = idProdutotxt.getText().matches("^[0-9]*$") ? Integer.parseInt(idProdutotxt.getText()) : 0;
        String nomeProdutoInformado = nomeProduto.getText();

        List<Produto> list = listaDeProdutos.stream()
                .filter(x -> x.getId() == idProdutoInformado || x.getNome().equals(nomeProdutoInformado))
                .collect(Collectors.toList());

        if (!list.isEmpty()) {
            produto = list.get(0);
        }

        if (produto != null) {

            cxdesconto.setText(produto.getDescricao());
            txtnomereduzido.setText(produto.getNome());
            txtapresentacao.setText(produto.getApresentacao());
            txtcomissao.setText(String.valueOf(produto.getComissao()));
            txtcodigo.setText(produto.getCodigoBarras());
            txtvalordecompra.setText(String.valueOf(produto.getValorDeCompra()));
            txtcustooperacional.setText(String.valueOf(produto.getCustoOperacional()));
            txtmargemdelucro.setText(String.valueOf(produto.getMargemDeLucro()));
            txtvaloravista.setText(String.valueOf(produto.getValorVista()));
            txtdesconto.setText(String.valueOf(produto.getDesconto()));
            txtvalordapromocao.setText(String.valueOf(produto.getValorPromocao()));
            txtultimoaumento.setText(produto.getUltimoAumento());
            txtvalidadedapromocao.setText(produto.getValidadePromocao());
            txtestoqueminimo.setText(String.valueOf(produto.getEstoqueMin()));
            txtaumentomaximo.setText(String.valueOf(produto.getEstoqueMax()));
            unidades.setSelectedItem((Object) produto.getUnidade());
            cxdesconto.setSelected(produto.isIsConvenio());

            if (produto.getTipoProduto() == 0) {
                btproduto.setSelected(true);
            } else {
                btservico.setSelected(true);
            }

            if (produto.getVendaDoProduto() == 0) {
                btquantidade.setSelected(true);
            } else {
                btvalor.setSelected(true);
            }

            if (produto.isIsEstoqueOnline()) {
                btestoquesim.setSelected(true);
            } else {
                btestoquenao.setSelected(true);
            }

            if (produto.getVendaDoProduto() == 0) {
                btquantidade.setSelected(true);
            } else {
                btvalor.setSelected(true);
            }

            if (produto.isIsPromocao()) {
                btpromocaosim.setSelected(true);
            } else {
                btpromocaonao.setSelected(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum produto com esse Id ou Nome");
        }

    }//GEN-LAST:event_buscarprodutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        ArrayList<Produto> listaDeProdutos = new ArrayList<Produto>();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduto().setVisible(true);
            }
        });
    }

    public static ArrayList<Produto> listaDeProdutos = new ArrayList<Produto>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JLabel apresentacao;
    private javax.swing.JRadioButton btestoquenao;
    private javax.swing.JRadioButton btestoquesim;
    private javax.swing.JRadioButton btproduto;
    private javax.swing.JRadioButton btpromocaonao;
    private javax.swing.JRadioButton btpromocaosim;
    private javax.swing.JRadioButton btquantidade;
    private javax.swing.JRadioButton btservico;
    private javax.swing.JRadioButton btvalor;
    private javax.swing.JButton buscarprodutos;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel codigodebarras;
    private javax.swing.JLabel comissao;
    private javax.swing.JLabel convenio;
    private javax.swing.JLabel custooperacional;
    private javax.swing.JCheckBox cxdesconto;
    private javax.swing.JLabel dadosprodutos;
    private javax.swing.JLabel desconto;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel estoquemaximo;
    private javax.swing.JLabel estoqueminimo;
    private javax.swing.JLabel estoqueonline;
    private javax.swing.ButtonGroup grupoestoque;
    private javax.swing.ButtonGroup grupopromocao;
    private javax.swing.ButtonGroup grupotipo;
    private javax.swing.ButtonGroup grupovenda;
    private javax.swing.JTextField idProdutotxt;
    private javax.swing.JLabel idprodutos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton listar;
    private javax.swing.JLabel margemdelucro;
    private javax.swing.JTextPane nomeProduto;
    private javax.swing.JLabel nomereduzido;
    private javax.swing.JLabel posicaodeestoque;
    private javax.swing.JLabel promocao;
    private javax.swing.JButton remover;
    private javax.swing.JButton sair;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextPane txtapresentacao;
    private javax.swing.JTextPane txtaumentomaximo;
    private javax.swing.JTextPane txtcodigo;
    private javax.swing.JScrollPane txtcodigodebarras;
    private javax.swing.JTextPane txtcomissao;
    private javax.swing.JTextPane txtcustooperacional;
    private javax.swing.JTextPane txtdesconto;
    private javax.swing.JTextPane txtdescricao;
    private javax.swing.JScrollPane txtestoquemaximo;
    private javax.swing.JTextPane txtestoqueminimo;
    private javax.swing.JTextPane txtmargemdelucro;
    private javax.swing.JTextPane txtnomereduzido;
    private javax.swing.JTextPane txtultimoaumento;
    private javax.swing.JTextPane txtvalidadedapromocao;
    private javax.swing.JTextPane txtvaloravista;
    private javax.swing.JTextPane txtvalordapromocao;
    private javax.swing.JTextPane txtvalordecompra;
    private javax.swing.JLabel unidade;
    private javax.swing.JComboBox<String> unidades;
    private javax.swing.JLabel validadedapromocao;
    private javax.swing.JLabel valoravista;
    private javax.swing.JLabel valordapromocao;
    private javax.swing.JLabel valordecompra;
    private javax.swing.JLabel valoresdevarejo;
    private javax.swing.JLabel vendadoproduto;
    // End of variables declaration//GEN-END:variables
}
