/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author GR2
 */
public class FormProduto extends javax.swing.JFrame {

    public ArrayList<Produto> listaDeProdutos = new ArrayList();

    /**
     * Creates new form Cadastrarproduto
     */
    public FormProduto() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupotipo = new javax.swing.ButtonGroup();
        grupovenda = new javax.swing.ButtonGroup();
        grupoestoque = new javax.swing.ButtonGroup();
        grupopromocao = new javax.swing.ButtonGroup();
        labelIdentificaoProduto = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNomeProduto = new javax.swing.JTextPane();
        labelDadosBasicos = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        labelNomeReduzido = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNomeReduzido = new javax.swing.JTextPane();
        labelUnidade = new javax.swing.JLabel();
        comboUnidades = new javax.swing.JComboBox<>();
        labelApresentacao = new javax.swing.JLabel();
        javax.swing.JLabel labelComissao = new javax.swing.JLabel();
        labelCodigoBarras = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtApresentacao = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtComissao = new javax.swing.JTextPane();
        txtcodigodebarras = new javax.swing.JScrollPane();
        txtCodigoDeBarras = new javax.swing.JTextPane();
        labelTipo = new javax.swing.JLabel();
        radioProduto = new javax.swing.JRadioButton();
        radioServico = new javax.swing.JRadioButton();
        labelVendaProduto = new javax.swing.JLabel();
        radioQuantidade = new javax.swing.JRadioButton();
        radioValor = new javax.swing.JRadioButton();
        labelEstoqueOnline = new javax.swing.JLabel();
        radioEstoqueSim = new javax.swing.JRadioButton();
        radioEstoqueNao = new javax.swing.JRadioButton();
        labelConvenio = new javax.swing.JLabel();
        checkboxDesconto = new javax.swing.JCheckBox();
        labelValoresVarejo = new javax.swing.JLabel();
        labelValorCompra = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtValorDeCompra = new javax.swing.JTextPane();
        labelCustoOperacional = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtCustoOperacional = new javax.swing.JTextPane();
        labelMargemLucro = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtMargemDeLucro = new javax.swing.JTextPane();
        labelValorVista = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtValorVista = new javax.swing.JTextPane();
        labelDesconto = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtDesconto = new javax.swing.JTextPane();
        labelPosicaoEstoque = new javax.swing.JLabel();
        labelEstoqueMinimo = new javax.swing.JLabel();
        txtestoquemaximo = new javax.swing.JScrollPane();
        txtEstoqueMinimo = new javax.swing.JTextPane();
        labelEstoqueMaximo = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtEstoqueMaximo = new javax.swing.JTextPane();
        labelUltimoAumento = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtUltimoAumento = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelPromocao = new javax.swing.JLabel();
        radioPromocaoNao = new javax.swing.JRadioButton();
        radioPromocaoSim = new javax.swing.JRadioButton();
        labelValorPromocao = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtValorDaPromocao = new javax.swing.JTextPane();
        labelValidadePromocao = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtValidadeDaPromocao = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelIdentificaoProduto.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelIdentificaoProduto.setForeground(new java.awt.Color(0, 0, 204));
        labelIdentificaoProduto.setText("Identificação do Produto");

        txtIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdutoActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.jpeg"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtNomeProduto);

        labelDadosBasicos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelDadosBasicos.setForeground(new java.awt.Color(0, 0, 204));
        labelDadosBasicos.setText("Dados Básicos");

        labelDescricao.setText("Descrição:");

        labelNomeReduzido.setText("Nome Reduzido:");

        jScrollPane2.setViewportView(txtDescricao);

        jScrollPane3.setViewportView(txtNomeReduzido);

        labelUnidade.setText("Unidade:");

        comboUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centímetro", "Metro", "Litro" }));
        comboUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUnidadesActionPerformed(evt);
            }
        });

        labelApresentacao.setText("Apresentação:");

        labelComissao.setText("Comissão:");

        labelCodigoBarras.setText("Código de Barras:");

        jScrollPane4.setViewportView(txtApresentacao);

        jScrollPane5.setViewportView(txtComissao);

        txtcodigodebarras.setViewportView(txtCodigoDeBarras);

        labelTipo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelTipo.setForeground(new java.awt.Color(0, 0, 204));
        labelTipo.setText("Tipo");

        grupotipo.add(radioProduto);
        radioProduto.setSelected(true);
        radioProduto.setText("Produto");
        radioProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioProdutoActionPerformed(evt);
            }
        });

        grupotipo.add(radioServico);
        radioServico.setText("Serviço");

        labelVendaProduto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelVendaProduto.setForeground(new java.awt.Color(0, 0, 204));
        labelVendaProduto.setText("Venda do Produto");

        grupovenda.add(radioQuantidade);
        radioQuantidade.setSelected(true);
        radioQuantidade.setText("Quantidade");
        radioQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioQuantidadeActionPerformed(evt);
            }
        });

        grupovenda.add(radioValor);
        radioValor.setText("Valor");

        labelEstoqueOnline.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelEstoqueOnline.setForeground(new java.awt.Color(0, 0, 204));
        labelEstoqueOnline.setText("Estoque On Line");

        grupoestoque.add(radioEstoqueSim);
        radioEstoqueSim.setText("Sim");

        grupoestoque.add(radioEstoqueNao);
        radioEstoqueNao.setSelected(true);
        radioEstoqueNao.setText("Não");

        labelConvenio.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelConvenio.setForeground(new java.awt.Color(0, 0, 204));
        labelConvenio.setText("Convênio");

        checkboxDesconto.setText("Desconto");
        checkboxDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDescontoActionPerformed(evt);
            }
        });

        labelValoresVarejo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelValoresVarejo.setForeground(new java.awt.Color(0, 0, 204));
        labelValoresVarejo.setText("Valores de Varejo");

        labelValorCompra.setText("Valor de Compra:");

        jScrollPane6.setViewportView(txtValorDeCompra);

        labelCustoOperacional.setText("Custo Operacional:");

        jScrollPane7.setViewportView(txtCustoOperacional);

        labelMargemLucro.setText("Margem de Lucro:");

        jScrollPane8.setViewportView(txtMargemDeLucro);

        labelValorVista.setText("Valor à Vista:");

        jScrollPane9.setViewportView(txtValorVista);

        labelDesconto.setText("Desconto:");

        jScrollPane10.setViewportView(txtDesconto);

        labelPosicaoEstoque.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelPosicaoEstoque.setForeground(new java.awt.Color(0, 0, 204));
        labelPosicaoEstoque.setText("Posição de Estoque");

        labelEstoqueMinimo.setText("Estoque Mínimo:");

        txtestoquemaximo.setViewportView(txtEstoqueMinimo);

        labelEstoqueMaximo.setText("Estoque Máximo:");

        jScrollPane14.setViewportView(txtEstoqueMaximo);

        labelUltimoAumento.setText("Último Aumento:");

        jScrollPane15.setViewportView(txtUltimoAumento);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemover.setText("REMOVER");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        labelPromocao.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelPromocao.setForeground(new java.awt.Color(0, 0, 204));
        labelPromocao.setText("Promoção:");

        grupopromocao.add(radioPromocaoNao);
        radioPromocaoNao.setSelected(true);
        radioPromocaoNao.setText("Não");
        radioPromocaoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPromocaoNaoActionPerformed(evt);
            }
        });

        grupopromocao.add(radioPromocaoSim);
        radioPromocaoSim.setText("Sim");
        radioPromocaoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPromocaoSimActionPerformed(evt);
            }
        });

        labelValorPromocao.setText("Valor da Promoção:");

        jScrollPane11.setViewportView(txtValorDaPromocao);

        labelValidadePromocao.setText("Validade da Promoção:");

        jScrollPane12.setViewportView(txtValidadeDaPromocao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValidadePromocao)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorPromocao)
                    .addComponent(radioPromocaoSim)
                    .addComponent(radioPromocaoNao)
                    .addComponent(labelPromocao))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelPromocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPromocaoNao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPromocaoSim)
                .addGap(18, 18, 18)
                .addComponent(labelValorPromocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelValidadePromocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboUnidades, 0, 241, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelApresentacao)
                                                .addGap(130, 130, 130)
                                                .addComponent(labelComissao))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelUnidade)
                                        .addGap(590, 590, 590)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCodigoBarras)
                                    .addComponent(txtcodigodebarras, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtestoquemaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radioProduto)
                                            .addComponent(radioServico))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelConvenio)
                                            .addComponent(checkboxDesconto))
                                        .addGap(92, 92, 92))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelPosicaoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelValorCompra)
                                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(labelCustoOperacional))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(labelMargemLucro))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelValorVista)
                                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelDesconto)
                                                    .addComponent(jScrollPane10)))
                                            .addComponent(labelValoresVarejo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(127, 127, 127)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addComponent(labelVendaProduto))
                                                    .addComponent(radioQuantidade)
                                                    .addComponent(radioValor))
                                                .addGap(75, 75, 75)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(radioEstoqueSim)
                                                    .addComponent(radioEstoqueNao)
                                                    .addComponent(labelEstoqueOnline))))
                                        .addGap(57, 57, 57)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDescricao)
                                        .addGap(302, 302, 302)
                                        .addComponent(labelNomeReduzido))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEstoqueMinimo)
                                        .addGap(85, 85, 85)
                                        .addComponent(labelEstoqueMaximo)
                                        .addGap(58, 58, 58)
                                        .addComponent(labelUltimoAumento)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDadosBasicos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdentificaoProduto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelIdentificaoProduto)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(labelDadosBasicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescricao)
                            .addComponent(labelNomeReduzido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUnidade)
                            .addComponent(labelApresentacao)
                            .addComponent(labelComissao)
                            .addComponent(labelCodigoBarras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcodigodebarras, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(comboUnidades))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelVendaProduto)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(radioQuantidade)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(radioValor))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelTipo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(radioProduto)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(radioServico)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelConvenio)
                                        .addGap(3, 3, 3)
                                        .addComponent(checkboxDesconto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEstoqueOnline)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioEstoqueNao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioEstoqueSim)))
                                .addGap(35, 35, 35)
                                .addComponent(labelValoresVarejo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelValorCompra)
                                    .addComponent(labelCustoOperacional)
                                    .addComponent(labelMargemLucro)
                                    .addComponent(labelValorVista)
                                    .addComponent(labelDesconto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(labelPosicaoEstoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelEstoqueMinimo)
                                    .addComponent(labelEstoqueMaximo)
                                    .addComponent(labelUltimoAumento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtestoquemaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUnidadesActionPerformed

    private void radioPromocaoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPromocaoNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPromocaoNaoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        Produto produto = new Produto();

        produto.setId(listaDeProdutos.size() == 0 ? 1 : listaDeProdutos.size() + 1);
        produto.setIsConvenio(checkboxDesconto.isSelected());
        produto.setDescricao(txtDescricao.getText());
        produto.setNome(txtNomeReduzido.getText());
        produto.setUnidade((String) comboUnidades.getSelectedItem());
        produto.setApresentacao(txtApresentacao.getText());
        produto.setComissao(Double.parseDouble(txtComissao.getText()));
        produto.setCodigoBarras(txtCodigoDeBarras.getText());
        produto.setTipoProduto(radioProduto.isSelected() ? 0 : 1);
        produto.setVendaDoProduto(radioQuantidade.isSelected() ? 0 : 1);
        produto.setIsEstoqueOnline(radioEstoqueSim.isSelected());
        produto.setIsPromocao(radioPromocaoSim.isSelected());
        produto.setValorDeCompra(Double.parseDouble(txtValorDeCompra.getText()));
        produto.setCustoOperacional(Double.parseDouble(txtCustoOperacional.getText()));
        produto.setMargemDeLucro(Double.parseDouble(txtMargemDeLucro.getText()));
        produto.setValorVista(Double.parseDouble(txtValorVista.getText()));
        produto.setDesconto(Double.parseDouble(txtDesconto.getText()));
        produto.setValorPromocao(Double.parseDouble(txtValorDaPromocao.getText()));
        produto.setEstoqueMin(Integer.parseInt(txtEstoqueMinimo.getText()));
        produto.setEstoqueMax(Integer.parseInt(txtEstoqueMaximo.getText()));
        produto.setUltimoAumento(txtUltimoAumento.getText());
        produto.setValidadePromocao(txtValidadeDaPromocao.getText());

        listaDeProdutos.add(produto);
        limparCampos();

    }//GEN-LAST:event_btnCadastrarActionPerformed

    public void limparCampos() {

        txtDescricao.setText("");
        checkboxDesconto.setSelected(false);
        txtNomeReduzido.setText("");
        comboUnidades.setSelectedItem((Object) "Centímetro");
        txtApresentacao.setText("");
        txtComissao.setText("");
        txtCodigoDeBarras.setText("");
        radioProduto.setSelected(true);
        radioServico.setSelected(false);
        radioQuantidade.setSelected(true);
        radioValor.setSelected(false);
        radioEstoqueSim.setSelected(false);
        radioEstoqueNao.setSelected(true);
        radioPromocaoSim.setSelected(false);
        radioPromocaoNao.setSelected(true);
        txtValorDeCompra.setText("");
        txtCustoOperacional.setText("");
        txtMargemDeLucro.setText("");
        txtValorVista.setText("");
        txtDesconto.setText("");
        txtValorDaPromocao.setText("");
        txtEstoqueMinimo.setText("");
        txtEstoqueMaximo.setText("");
        txtUltimoAumento.setText("");
        txtValidadeDaPromocao.setText("");

    }

    private void checkboxDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxDescontoActionPerformed

    private void radioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioProdutoActionPerformed

    private void radioQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioQuantidadeActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        String listagem = "Itens Listados: " + "\n" + "\n";

        for (Produto produto : listaDeProdutos) {
            listagem += produto.getId() + "." + " Nome: " + produto.getNome() + "\n"
                    + "Descrição: " + produto.getDescricao() + "\n" + "\n";
        }

        System.out.println(listagem);
        JOptionPane.showMessageDialog(null, listagem);

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        
        int idProdutoInformado = txtIdProduto.getText().matches("^[0-9]*$") ? Integer.parseInt(txtIdProduto.getText()) : 0;
        listaDeProdutos.removeIf(x -> x.getId() == idProdutoInformado);
        limparCampos();
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void radioPromocaoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPromocaoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPromocaoSimActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        int idProdutoInformado = txtIdProduto.getText().matches("^[0-9]*$") ? Integer.parseInt(txtIdProduto.getText()) : 0;

        for (Produto produto : listaDeProdutos) {

            if (produto.getId() == idProdutoInformado) {

                produto.setIsConvenio(checkboxDesconto.isSelected());
                produto.setDescricao(txtDescricao.getText());
                produto.setNome(txtNomeReduzido.getText());
                produto.setUnidade((String) comboUnidades.getSelectedItem());
                produto.setApresentacao(txtApresentacao.getText());
                produto.setComissao(Double.parseDouble(txtComissao.getText()));
                produto.setCodigoBarras(txtCodigoDeBarras.getText());
                produto.setTipoProduto(radioProduto.isSelected() ? 0 : 1);
                produto.setVendaDoProduto(radioQuantidade.isSelected() ? 0 : 1);
                produto.setIsEstoqueOnline(radioEstoqueSim.isSelected());
                produto.setIsPromocao(radioPromocaoSim.isSelected());
                produto.setValorDeCompra(Double.parseDouble(txtValorDeCompra.getText()));
                produto.setCustoOperacional(Double.parseDouble(txtCustoOperacional.getText()));
                produto.setMargemDeLucro(Double.parseDouble(txtMargemDeLucro.getText()));
                produto.setValorVista(Double.parseDouble(txtValorVista.getText()));
                produto.setDesconto(Double.parseDouble(txtDesconto.getText()));
                produto.setValorPromocao(Double.parseDouble(txtValorDaPromocao.getText()));
                produto.setEstoqueMin(Integer.parseInt(txtEstoqueMinimo.getText()));
                produto.setEstoqueMax(Integer.parseInt(txtEstoqueMaximo.getText()));
                produto.setUltimoAumento(txtUltimoAumento.getText());
                produto.setValidadePromocao(txtValidadeDaPromocao.getText());

            }
        }

        limparCampos();
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdutoActionPerformed
    }//GEN-LAST:event_txtIdProdutoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        Produto produto = null;
        int idProdutoInformado = txtIdProduto.getText().matches("^[0-9]*$") ? Integer.parseInt(txtIdProduto.getText()) : 0;
        String nomeProdutoInformado = txtNomeProduto.getText();

        List<Produto> list = listaDeProdutos.stream()
                .filter(x -> x.getId() == idProdutoInformado || x.getNome().equals(nomeProdutoInformado))
                .collect(Collectors.toList());

        if (!list.isEmpty()) {
            produto = list.get(0);
        }

        if (produto != null) {

            txtDescricao.setText(produto.getDescricao());
            txtNomeReduzido.setText(produto.getNome());
            txtApresentacao.setText(produto.getApresentacao());
            txtComissao.setText(String.valueOf(produto.getComissao()));
            txtCodigoDeBarras.setText(produto.getCodigoBarras());
            txtValorDeCompra.setText(String.valueOf(produto.getValorDeCompra()));
            txtCustoOperacional.setText(String.valueOf(produto.getCustoOperacional()));
            txtMargemDeLucro.setText(String.valueOf(produto.getMargemDeLucro()));
            txtValorVista.setText(String.valueOf(produto.getValorVista()));
            txtDesconto.setText(String.valueOf(produto.getDesconto()));
            txtValorDaPromocao.setText(String.valueOf(produto.getValorPromocao()));
            txtUltimoAumento.setText(produto.getUltimoAumento());
            txtValidadeDaPromocao.setText(produto.getValidadePromocao());
            txtEstoqueMinimo.setText(String.valueOf(produto.getEstoqueMin()));
            txtEstoqueMaximo.setText(String.valueOf(produto.getEstoqueMax()));
            comboUnidades.setSelectedItem((Object) produto.getUnidade());
            checkboxDesconto.setSelected(produto.isIsConvenio());

            if (produto.getTipoProduto() == 0) {
                radioProduto.setSelected(true);
            } else {
                radioServico.setSelected(true);
            }

            if (produto.getVendaDoProduto() == 0) {
                radioQuantidade.setSelected(true);
            } else {
                radioValor.setSelected(true);
            }

            if (produto.isIsEstoqueOnline()) {
                radioEstoqueSim.setSelected(true);
            } else {
                radioEstoqueNao.setSelected(true);
            }

            if (produto.getVendaDoProduto() == 0) {
                radioQuantidade.setSelected(true);
            } else {
                radioValor.setSelected(true);
            }

            if (produto.isIsPromocao()) {
                radioPromocaoSim.setSelected(true);
            } else {
                radioPromocaoNao.setSelected(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado!");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduto().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBox checkboxDesconto;
    private javax.swing.JComboBox<String> comboUnidades;
    private javax.swing.ButtonGroup grupoestoque;
    private javax.swing.ButtonGroup grupopromocao;
    private javax.swing.ButtonGroup grupotipo;
    private javax.swing.ButtonGroup grupovenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labelApresentacao;
    private javax.swing.JLabel labelCodigoBarras;
    private javax.swing.JLabel labelConvenio;
    private javax.swing.JLabel labelCustoOperacional;
    private javax.swing.JLabel labelDadosBasicos;
    private javax.swing.JLabel labelDesconto;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelEstoqueMaximo;
    private javax.swing.JLabel labelEstoqueMinimo;
    private javax.swing.JLabel labelEstoqueOnline;
    private javax.swing.JLabel labelIdentificaoProduto;
    private javax.swing.JLabel labelMargemLucro;
    private javax.swing.JLabel labelNomeReduzido;
    private javax.swing.JLabel labelPosicaoEstoque;
    private javax.swing.JLabel labelPromocao;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelUltimoAumento;
    private javax.swing.JLabel labelUnidade;
    private javax.swing.JLabel labelValidadePromocao;
    private javax.swing.JLabel labelValorCompra;
    private javax.swing.JLabel labelValorPromocao;
    private javax.swing.JLabel labelValorVista;
    private javax.swing.JLabel labelValoresVarejo;
    private javax.swing.JLabel labelVendaProduto;
    private javax.swing.JRadioButton radioEstoqueNao;
    private javax.swing.JRadioButton radioEstoqueSim;
    private javax.swing.JRadioButton radioProduto;
    private javax.swing.JRadioButton radioPromocaoNao;
    private javax.swing.JRadioButton radioPromocaoSim;
    private javax.swing.JRadioButton radioQuantidade;
    private javax.swing.JRadioButton radioServico;
    private javax.swing.JRadioButton radioValor;
    private javax.swing.JTextPane txtApresentacao;
    private javax.swing.JTextPane txtCodigoDeBarras;
    private javax.swing.JTextPane txtComissao;
    private javax.swing.JTextPane txtCustoOperacional;
    private javax.swing.JTextPane txtDesconto;
    private javax.swing.JTextPane txtDescricao;
    private javax.swing.JTextPane txtEstoqueMaximo;
    private javax.swing.JTextPane txtEstoqueMinimo;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextPane txtMargemDeLucro;
    private javax.swing.JTextPane txtNomeProduto;
    private javax.swing.JTextPane txtNomeReduzido;
    private javax.swing.JTextPane txtUltimoAumento;
    private javax.swing.JTextPane txtValidadeDaPromocao;
    private javax.swing.JTextPane txtValorDaPromocao;
    private javax.swing.JTextPane txtValorDeCompra;
    private javax.swing.JTextPane txtValorVista;
    private javax.swing.JScrollPane txtcodigodebarras;
    private javax.swing.JScrollPane txtestoquemaximo;
    // End of variables declaration//GEN-END:variables
}
